"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "DJANGO_SECRET_KEY",
    default="django-insecure-6c@-rw4qbkwqa%=ir@sehnyx2d63&0tqy48im-)cw9-61+aec@",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DJANGO_DEBUG", default=True, cast=bool)

# Parse comma-separated hosts from environment for safer local/prod switching.
ALLOWED_HOSTS = config(
    "DJANGO_ALLOWED_HOSTS",
    default="localhost,127.0.0.1,mysite.com",
    cast=lambda value: [host.strip() for host in value.split(",") if host.strip()],
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.sitemaps",
    "django.contrib.staticfiles",
    "accounts.apps.AccountsConfig",
    "django_icons",
    "social_django",
    "taggit",
    "recipes.apps.RecipesConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if DEBUG:
    INSTALLED_APPS += ["debug_toolbar"]
    MIDDLEWARE.insert(1, "debug_toolbar.middleware.DebugToolbarMiddleware")

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "social_django.context_processors.backends",
                "social_django.context_processors.login_redirect",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("POSTGRES_DB", default="kapykitchen"),
        "USER": config("POSTGRES_USER", default="mina"),
        "PASSWORD": config("POSTGRES_PASSWORD", default="blah"),
        "HOST": config("POSTGRES_HOST", default="127.0.0.1"),
        "PORT": config("POSTGRES_PORT", default="5432"),
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": config("REDIS_URL", default="redis://127.0.0.1:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": True,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/Chicago"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Use an absolute URL path so static assets resolve correctly
# in development and production (e.g., /static/recipes/style.css)
STATIC_URL = "/static/"

INTERNAL_IPS = ["127.0.0.1"]

DJANGO_ICONS = {
    "ICONS": {
        "search": {"name": "fa-solid fa-magnifying-glass"},
        "hungry": {"name": "fa-solid fa-shuffle"},
        "home": {"name": "fa-solid fa-house"},
        "recipes": {"name": "fa-solid fa-book-open"},
        "login": {"name": "fa-solid fa-right-to-bracket"},
        "logout": {"name": "fa-solid fa-right-from-bracket"},
        "calendar": {"name": "fa-regular fa-calendar"},
        "author": {"name": "fa-regular fa-user"},
        "servings": {"name": "fa-solid fa-bowl-food"},
        "time": {"name": "fa-regular fa-clock"},
        "tags": {"name": "fa-solid fa-tags"},
        "view": {"name": "fa-solid fa-arrow-up-right-from-square"},
        "previous": {"name": "fa-solid fa-chevron-left"},
        "next": {"name": "fa-solid fa-chevron-right"},
        "ingredients": {"name": "fa-solid fa-carrot"},
        "steps": {"name": "fa-solid fa-list-ol"},
        "comments": {"name": "fa-regular fa-comments"},
        "comment": {"name": "fa-regular fa-comment"},
        "check": {"name": "fa-solid fa-circle-check"},
        "warning": {"name": "fa-solid fa-triangle-exclamation"},
        "google": {"name": "fa-brands fa-google"},
        "sparkles": {"name": "fa-solid fa-wand-magic-sparkles"},
        "cozy": {"name": "fa-solid fa-mug-hot"},
        "easy": {"name": "fa-solid fa-feather-pointed"},
        "tips": {"name": "fa-solid fa-lightbulb"},
        "no_results": {"name": "fa-regular fa-face-frown"},
    }
}

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "social_core.backends.google.GoogleOAuth2",
]

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config("GOOGLE_OAUTH2_KEY", default="")
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config("GOOGLE_OAUTH2_SECRET", default="")
