# Generated by Django 6.0.1 on 2026-01-29 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="post",
            new_name="recipes_pos_publish_286616_idx",
            old_name="recipes_post_publish_bb7600_idx",
        ),
        migrations.RemoveField(
            model_name="post",
            name="body",
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
