# Generated by Django 6.0.1 on 2026-01-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="instructions",
            field=models.TextField(
                blank=True, help_text="Step-by-step instructions", null=True
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="servings",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of servings", null=True
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="substitution",
            field=models.TextField(
                blank=True,
                help_text="Ingredient substitutions or alternatives",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="time",
            field=models.PositiveIntegerField(
                blank=True, help_text="Preparation/cook time in minutes", null=True
            ),
        ),
    ]
