# Generated by Django 6.0.1 on 2026-02-25 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_ingredient_recipeingredient_recipestep"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="instructions",
        ),
        migrations.RemoveField(
            model_name="post",
            name="substitution",
        ),
    ]
