# Generated by Django 6.0.1 on 2026-04-28 22:15

from django.db import migrations, models


def populate_recipe_counts(apps, schema_editor):
    Post = apps.get_model("recipes", "Post")
    RecipeIngredient = apps.get_model("recipes", "RecipeIngredient")
    Comment = apps.get_model("recipes", "Comment")

    for post in Post.objects.all():
        ingredient_count = RecipeIngredient.objects.filter(post_id=post.pk).count()
        comment_count = Comment.objects.filter(post_id=post.pk, active=True).count()

        Post.objects.filter(pk=post.pk).update(
            ingredient_count=ingredient_count,
            comment_count=comment_count,
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_add_tags_to_placeholder_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='ingredient_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='posts', through='recipes.RecipeIngredient', to='recipes.ingredient'),
        ),
        migrations.RunPython(populate_recipe_counts, noop),
    ]
